### ISSUE TITLE
Test with Mister Ouahid 🎤

### ISSUE THREAD

**Issue by T3kstiil3** [ytvnr/gif-of-the-day#112]
# Round 1

- [x] Loader after login success to prevent clic clic / before auto login #117
- [x] Choose a theme need to be disabled if no team select ! https://github.com/ytvnr/gif-of-the-day/pull/114
      - home tile
      - menu list
      - page guard
- [x] Schedule fix column size to prevent move #118
- [x] Home move random gif into card #116
- [ ] Bug keep last view page broken
- [ ] Look about redirection in the router
- [x] Rework on home tiles order **-> Waiting for the others to be merged** 🚧 and resolve in the same time https://github.com/ytvnr/gif-of-the-day/issues/102 https://github.com/ytvnr/gif-of-the-day/pull/120
- [x] Footer link to issue need to redirect to issues/choose #115

# Round 2

- [x] Limit theme size to 20 #123
- [x] Keep the schedule header (table) in extension mode #125 
- [ ] Team card need to be more large
- [x] Home gif card add margin left and right #123
- [ ] Test extension with Firefox 🦊
- [x] Add scope to all style part components 👮‍♂️ #123
- [x] Remove login with Github logo #123
- [x] Fix dev mode in production d instead of p ⚠️ #119 
- [x] Update app favicon #126
